packages:
  - "packages/*"
allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  agent-browser: true
  argon2: false
  bufferutil: true
  edgedriver: false
  electron: true
  electron-winstaller: false
  esbuild: true
  geckodriver: false
  koffi: true
  msgpackr-extract: true
  onnxruntime-node: true
  protobufjs: true
  sharp: false
  tree-sitter-python: true
minimumReleaseAgeExclude:
  - '@mastra/core@1.42.0'
