packages:
  - "packages/*"
allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  agent-browser: true
  argon2: false
  bufferutil: true
  edgedriver: false
  electron: true
  electron-winstaller: false
  esbuild: true
  geckodriver: false
  koffi: true
  msgpackr-extract: true
  onnxruntime-node: true
  protobufjs: true
  sharp: false
  tree-sitter-python: true
minimumReleaseAgeExclude:
  - '@mastra/core@1.42.0'
  - '@codingame/monaco-vscode-api@34.1.1'
  - '@codingame/monaco-vscode-base-service-override@34.1.1'
  - '@codingame/monaco-vscode-configuration-service-override@34.1.1'
  - '@codingame/monaco-vscode-editor-api@34.1.1'
  - '@codingame/monaco-vscode-environment-service-override@34.1.1'
  - '@codingame/monaco-vscode-extensions-service-override@34.1.1'
  - '@codingame/monaco-vscode-files-service-override@34.1.1'
  - '@codingame/monaco-vscode-host-service-override@34.1.1'
  - '@codingame/monaco-vscode-javascript-default-extension@34.1.1'
  - '@codingame/monaco-vscode-json-default-extension@34.1.1'
  - '@codingame/monaco-vscode-keybindings-service-override@34.1.1'
  - '@codingame/monaco-vscode-layout-service-override@34.1.1'
  - '@codingame/monaco-vscode-quickaccess-service-override@34.1.1'
  - '@codingame/monaco-vscode-textmate-service-override@34.1.1'
  - '@codingame/monaco-vscode-theme-defaults-default-extension@34.1.1'
  - '@codingame/monaco-vscode-theme-service-override@34.1.1'
  - '@codingame/monaco-vscode-typescript-basics-default-extension@34.1.1'
